import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

/*
 * The service-role client bypasses RLS entirely. Only the cron job and the
 * Stripe webhook run without a user session and legitimately need it;
 * everywhere else it would silently disable every access rule the product is
 * sold on.
 */
const noServiceRoleClient = {
  group: ['**/supabase/admin', '@/lib/supabase/admin'],
  message:
    'The service-role client bypasses RLS. Only app/api/cron/** and app/api/webhooks/** may import it. See docs/sot/20-architecture.md.',
}

/*
 * Money is held by three deterministic layers — pure functions with unit tests,
 * database triggers, and column constraints — and lib/domain is the first of
 * them. AI output is non-deterministic and is only ever a SUGGESTION that a
 * person confirms (D25); wiring it into the arithmetic would spoil the most
 * expensive thing this project bought. The boundary is compiled rather than
 * written down because a promise nobody enforces is just a sentence in
 * docs/sot/40-decisions.md, and the person who breaks it will be the one who
 * never read it.
 */
const noAiInDomain = {
  group: ['@/lib/ai', '@/lib/ai/**', '**/lib/ai', '**/lib/ai/**', '../ai', '../ai/**'],
  message:
    'lib/domain is the deterministic money path and must not import lib/ai. AI output is a suggestion a person confirms, never an input to a calculation. See D25 in docs/sot/40-decisions.md.',
}

/**
 * eslint-config-next 16 ships native flat configs, so they are imported
 * directly. Do not reintroduce @eslint/eslintrc's FlatCompat here — wrapping an
 * already-flat config makes ESLint 10 fail while serialising the plugin graph.
 */
const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
      'supabase/.temp/**', // scratch files written by the Supabase CLI
      'supabase/.branches/**',
      'lib/types/database.ts', // generated by `pnpm db:types`
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    /*
     * This rule is what makes the service-role guarantee survive a new
     * contributor who has not read docs/sot/20-architecture.md.
     */
    files: ['app/**', 'components/**', 'lib/**'],
    ignores: ['app/api/cron/**', 'app/api/webhooks/**', 'lib/supabase/admin.ts'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noServiceRoleClient] }],
    },
  },
  {
    /*
     * lib/domain carries BOTH restrictions. Flat config overrides a rule's
     * options rather than merging them, so this block has to restate the
     * service-role pattern — hence the shared constants above. Listing it
     * literally a second time would be the two-sources-of-truth bug the rule
     * itself exists to prevent.
     */
    files: ['lib/domain/**'],
    rules: {
      'no-restricted-imports': ['error', { patterns: [noServiceRoleClient, noAiInDomain] }],
    },
  },
]

export default eslintConfig
