import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypeScript from 'eslint-config-next/typescript'

/**
 * eslint-config-next 16 ships native flat configs, so they are imported
 * directly. Do not reintroduce @eslint/eslintrc's FlatCompat here — wrapping an
 * already-flat config makes ESLint 10 fail while serialising the plugin graph.
 */
const eslintConfig = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
      'supabase/.temp/**', // scratch files written by the Supabase CLI
      'supabase/.branches/**',
      'lib/types/database.ts', // generated by `pnpm db:types`
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    /*
     * The service-role client bypasses RLS entirely. Only the cron job and the
     * Stripe webhook run without a user session and legitimately need it;
     * everywhere else it would silently disable every access rule the product
     * is sold on. This rule is what makes that guarantee survive a new
     * contributor who has not read docs/sot/20-architecture.md.
     */
    files: ['app/**', 'components/**', 'lib/**'],
    ignores: ['app/api/cron/**', 'app/api/webhooks/**', 'lib/supabase/admin.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/supabase/admin', '@/lib/supabase/admin'],
              message:
                'The service-role client bypasses RLS. Only app/api/cron/** and app/api/webhooks/** may import it. See docs/sot/20-architecture.md.',
            },
          ],
        },
      ],
    },
  },
]

export default eslintConfig
