import { PLAN_IDS, isPlanId, type PlanId } from '@/lib/domain/plan-limits'

/**
 * The three plans, as they exist inside Stripe.
 *
 * NO PRICE ID IS EVER WRITTEN DOWN. Ids like `price_1P...` are generated by
 * Stripe, differ between test mode and live mode, and differ again for anyone
 * who recreates them — so a hard-coded one is a value that is correct exactly
 * once, on one machine, until somebody clears their test data. Instead each
 * plan owns two stable names that WE choose:
 *
 *   product id   `rentease_mini`             — Stripe lets a product be created
 *                                              with an id we supply, so the same
 *                                              name always means the same product
 *   price lookup key `rentease_mini_monthly` — Stripe's documented handle for
 *                                              "the current price of this thing"
 *
 * ensurePlanPrice() in ./provisioning.ts resolves a lookup key to whatever
 * price id it points at today, and creates the product and price the first
 * time it finds nothing. That makes it idempotent by construction rather than
 * by remembering to run a setup script exactly once: call it a hundred times
 * and there is still one product and one price per plan.
 *
 * THIS FILE STAYS PURE. It names things and reads a price object; it never
 * calls Stripe. lib/stripe/events.ts needs the naming to tell which plan a
 * webhook payload is about, and a webhook payload can arrive on a server with
 * no Stripe key at all — importing the SDK here would make that impossible,
 * and would drag the whole client into the unit tests.
 *
 * It also means changing a price later is a Stripe-side operation — create the
 * new price with `transfer_lookup_key`, and the next checkout picks it up with
 * no deploy. D5 says the numbers are configuration; this is what makes that
 * true.
 *
 * (The deploy runbook stream 3B is writing can call ensureAllPlanPrices() once
 * against a live-mode key to have everything in place before the first customer
 * arrives, rather than letting the first checkout create it.)
 */

/** Stable product ids. Ours, not Stripe's. */
export const PRODUCT_IDS: Readonly<Record<PlanId, string>> = {
  mini: 'rentease_mini',
  standard: 'rentease_standard',
  pro: 'rentease_pro',
}

/** Stable price lookup keys. Ours, not Stripe's. */
export const PRICE_LOOKUP_KEYS: Readonly<Record<PlanId, string>> = {
  mini: 'rentease_mini_monthly',
  standard: 'rentease_standard_monthly',
  pro: 'rentease_pro_monthly',
}

const LOOKUP_KEY_TO_PLAN: ReadonlyMap<string, PlanId> = new Map(
  PLAN_IDS.map((id) => [PRICE_LOOKUP_KEYS[id], id]),
)

/**
 * Which plan a Stripe price belongs to.
 *
 * Tried in the order things are most likely to still be true: the lookup key we
 * chose, then the product id we chose, then metadata. All three are written by
 * this module, so agreeing is the normal case — the fallbacks exist for a price
 * created by hand in the Stripe dashboard, where only one of them may be set.
 */
export function planForPriceLike(price: {
  lookup_key?: string | null
  product?: string | { id?: string } | null
  metadata?: Record<string, string> | null
}): PlanId | null {
  if (price.lookup_key) {
    const byLookup = LOOKUP_KEY_TO_PLAN.get(price.lookup_key)
    if (byLookup) return byLookup
  }

  const productId = typeof price.product === 'string' ? price.product : price.product?.id
  if (productId) {
    const match = PLAN_IDS.find((id) => PRODUCT_IDS[id] === productId)
    if (match) return match
  }

  const fromMetadata = price.metadata?.plan
  if (isPlanId(fromMetadata)) return fromMetadata

  return null
}
